### ISSUE TITLE
启动报错啊

### ISSUE THREAD

**Issue by qiyue520** [Evil0ctal/TikTokDownloader_PyWebIO#11]
PermissionError: [Errno 13] Permission denied: 'logs.txt'

**Comment by Evil0ctal** [comment]
> PermissionError: [Errno 13] Permission denied: 'logs.txt'

使用root权限跑一下

`sudo python3 TikTok_ZH.py`

**Comment by qiyue520** [comment]
手动创建文件夹就好了,如果nginx绑定了多个域名,发现只适合做反代 127.0.0.1:5000
