### ISSUE TITLE
tiktok无水印视频接口好像无法访问了，请问是我梯子的问题吗？

### ISSUE THREAD

**Issue by Michael-YYang** [Evil0ctal/TikTokDownloader_PyWebIO#2]
HTTPSConnectionPool(host='toolav.herokuapp.com', port=443): Max retries exceeded with url: /id/?video_id=7044801419366616367 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BFA7D27D30>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Comment by Evil0ctal** [comment]
不是你的问题，应该是对面的服务器down了，TikTok的解析我会尽快修复：）

**Comment by Michael-YYang** [comment]
> 



> 不是你的问题，应该是后期的服务器了，TikTok的解析我会很快修复：）

非常感谢

**Comment by Evil0ctal** [comment]
> 

你好，解析失败的问题已经修复了，但是频繁的解析TikTok可能触发TikTok限流导致解析失败，需要等待1-2分钟后再次尝试，圣诞节快乐！🎄
