### ISSUE TITLE
Tiktok无水印挂了

### ISSUE THREAD

**Issue by tpyu** [Evil0ctal/TikTokDownloader_PyWebIO#3]
啥时候修复啊

**Comment by Evil0ctal** [comment]
> 啥时候修复啊

你好，最近在过年，加上TikTok修改了API，可能需要过一段时间，目前其他的开发者也没有更新TikTok的爬虫，如果你知道哪些项目仍能爬取TikTok，可以在下面回复我，我会尽快修复这个问题，除夕快乐！

**Comment by Evil0ctal** [comment]
> 啥时候修复啊

你好，现在应该可以解析TikTok了，新年快乐！
