### ISSUE TITLE
演示站521了

### ISSUE THREAD

**Issue by hankepython** [Evil0ctal/TikTokDownloader_PyWebIO#9]
如题

**Comment by Evil0ctal** [comment]
> 如题

感谢反馈，最近douyin.wtf用的人比较多了，现在这台小机子只有500M的内存，在调用`/video?url=“链接”`这个接口时，程序会先下载该视频转换为二进制并写入内存中，最后make一个response给浏览器，然后可能服务器内存爆了导致进程终止，过段时间我会把它跑在内存更大的服务器上。

**Comment by hankepython** [comment]
> 

好了，修复了

**Comment by hankepython** [comment]
> > 如题
> 
> 感谢反馈，最近douyin.wtf用的人比较多了，现在这台小机子只有500M的内存，在调用`/video?url=“链接”`这个接口时，程序会先下载该视频转换为二进制并写入内存中，最后make一个response给浏览器，然后可能服务器内存爆了导致进程终止，过段时间我会把它跑在内存更大的服务器上。

又521了，麻烦你了

**Comment by Evil0ctal** [comment]
> > > 如题
> 
> > 
> 
> > 感谢反馈，最近douyin.wtf用的人比较多了，现在这台小机子只有500M的内存，在调用`/video?url=“链接”`这个接口时，程序会先下载该视频转换为二进制并写入内存中，最后make一个response给浏览器，然后可能服务器内存爆了导致进程终止，过段时间我会把它跑在内存更大的服务器上。
> 
> 
> 
> 又521了，麻烦你了

好的，我晚点去解决，感谢反馈。
